#define AND                              1
#define OR                               2
#define EQ                               3
#define NE                               4
#define GT                               5
#define GE                               6
#define LT                               7
#define LE                               8
#define IN                               9
#define LIKE                            10
#define STRING                          11
#define LP                              12
#define RP                              13
#define INTEGER                         14
#define FLOAT                           15
#define TRUE                            16
#define FALSE                           17
#define COMMA                           18
#define ENUMERATOR                      19
