#define AND                              1
#define OR                               2
#define EQ                               3
#define NE                               4
#define GT                               5
#define GE                               6
#define LT                               7
#define LE                               8
#define IN                               9
#define LP                              10
#define RP                              11
#define INTEGER                         12
#define STRING                          13
#define FLOAT                           14
#define COMMA                           15
#define ENUMERATOR                      16
