#define AND                              1
#define OR                               2
#define EQ                               3
#define NE                               4
#define GT                               5
#define GE                               6
#define LT                               7
#define LE                               8
#define LP                               9
#define RP                              10
#define INTEGER                         11
#define STRING                          12
#define FLOAT                           13
#define ENUMERATOR                      14
