#define LP                               1
#define RP                               2
#define COMMA                            3
#define IDENT                            4
#define ENUMERATOR                       5
#define IDENTT                           6
#define INTEGER                          7
#define STRING                           8
#define FLOAT                            9
#define TRUE                            10
#define FALSE                           11
